Update the parachain template to stable2412 (#26)
Signed-off-by: Iulian Barbu <iulian.barbu@parity.io>

diff --git a/.github/workflows/test-zombienet.yml b/.github/workflows/test-zombienet.yml
--- a/.github/workflows/test-zombienet.yml
+++ b/.github/workflows/test-zombienet.yml
@@ -37,6 +37,15 @@ jobs:
       - name: Run zombienet tests
         run: |
           export PATH="./target/release:$PATH"
-          npx --yes @zombienet/cli --provider native test .github/tests/zombienet-smoke-test.zndsl
+          rm -fr /tmp/zn-test || echo "No test directory to remove"
+          npx --yes @zombienet/cli --dir /tmp/zn-test --provider native test .github/tests/zombienet-smoke-test.zndsl # || echo "Tests failed - proceeding to logs uploading"
         shell: bash
-        timeout-minutes: 10
+        timeout-minutes: 60
+      - name: Upload logs
+        uses: actions/upload-artifact@v4.3.6
+        with:
+          name: zn-test-logs
+          path: |
+            /tmp/zn-test/logs/alice.log
+            /tmp/zn-test/logs/bob.log
+            /tmp/zn-test/logs/charlie.log
